name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DBIMEUP_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j 2

      - name: Test
        working-directory: build
        run: ctest --output-on-failure --build-config ${{ matrix.build_type }}
